### ISSUE TITLE
Can you please add me as a collaborator

### ISSUE THREAD

**Issue by goru001** [anuragshas/nlp-for-urdu#1]
@anuragshas Can you please add me as a collaborator to this repository? I was adding Embedding Projections to all the repos whose models are being used in iNLTK. That requires me to push ~50-60Mb file of tensors to github, for which lfs should be enabled. And as documented [here](https://github.com/git-lfs/git-lfs/issues/1906), Git LFS on github.com does not currently support pushing LFS objects to public forks.

**Comment by anuragshas** [comment]
I have sent you the invite

**Comment by goru001** [comment]
thanks Anurag!
